name: WatchDog
main: com.section214.watchdog.WatchDog
version: 1.0.0
author: Section214
website: http://section214.com
description: Allows server staff to add players to a watchlist and receive notifications when they login
dev-url: http://dev.bukkit.org/server-mods/watchdog/

commands:
    wd:
        description: 'WatchDog plugin commands'
        aliases: [watchdog]
        
permissions:
    watchdog.*:
        default: false
        description: Implies all WatchDog permissions
        children:
            watchdog.use: true
            watchdog.add: true
            watchdog.remove: true
            watchdog.statusupdates: true
    watchdog.use:
        default: false
        description: Allows user to use WatchDog
    watchdog.add:
        default: false
        description: Allows user to add a player to the watchlist
        children:
            watchdog.use: true
    watchdog.remove:
        default: false
        description: Allows user to remove a player from the watchlist
        children:
            watchdog.use: true
            watchdog.add: true
    watchdog.statusupdates:
        default: false
        description: Allows user to be informed when watched players login
        children:
            watchdog.use: true
